name: homathon_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # cupertino icons
  cupertino_icons: ^0.1.2
  # provider
  provider: ^4.0.5
  # provider architecture
  provider_architecture: ^1.0.6
  #get it
  get_it: ^4.0.1
  # giffy dialog
  giffy_dialog: ^1.7.0
  # flutter toast
  fluttertoast: ^4.0.1
  # url launcher
  url_launcher: ^5.4.2
  # font awesome flutter
  font_awesome_flutter: ^8.8.1
  # google maps flutter
  google_maps_flutter: ^0.5.26+2
  # timeline list
  timeline_list: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter launcher icons
  flutter_launcher_icons: ^0.7.4

# flutter_icons:
#   ios: false
#   android: "launcher_icon"
#   image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/gif/
    - assets/images/defaults/
    - assets/map_styles/

  fonts:
    - family: Gibson
      fonts:
        - asset: assets/fonts/gibson_regular.ttf
        - asset: assets/fonts/gibson_regular_italic.ttf
          style: italic
        - asset: assets/fonts/gibson_bold.ttf
          weight: 700
